name: cli-tests

on:
  push:
  schedule:
    - cron: "0 2 * * 1" # The task runs at 2 a.m. every Monday.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Bash on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -e .
      - name: Install weasyprint on macos-latest
        if: runner.os == 'macOS'
        run: |
          brew install weasyprint
      - name: Run tests append
        run: sh tests/append/tests.sh
      - name: Run tests version
        run: sh tests/test_version.sh
